version: "3.9"

services:
  djangoapp:
    container_name: djangoapp
    build: .
    environment:
      - PG_USER=root
      - PG_PASSWORD=thanhvy2002@
      - PG_DB=postgres
      - PG_PORT=5432
      - PG_HOST=db
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:12
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=thanhvy2002@
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}